// Note on A.I. usage:
// As allowed in the assignment instructions, I used AI to remind me of syntax
    // I would have an idea already of what I wanted and ask AI how to type it out correctly
// I also used AI to troubleshoot errors in code I previously attempted to write
    // AI often returned corrected code which I evaluated, learned from, and manually
    // typed into the program. No code was copy and pasted from any other source.

// These processes were bypassed only by the creation of the 'exercises' array, which
// was generated by ChatGPT and copy/pasted in. To my memory, this was given allowance
// verbally in class.

// All images were also generated by ChatGPT


// Exercises array
const exercises = [
  {
    name: "Squat",
    description: "A compound lower-body movement targeting the legs and hips by bending at the knees and hips while keeping the torso upright.",
    image: "images/squat.png",
    alt: "Person performing a barbell squat with the bar on their upper back, lowering hips below parallel while keeping chest upright.",
    muscleGroups: ["quadriceps", "glutes", "hamstrings", "core"]
  },
  {
    name: "Bench Press",
    description: "A compound upper-body exercise where you press a barbell or dumbbells upward while lying on a bench.",
    image: "images/bench.png",
    alt: "Person lying on a bench pressing a barbell upward over their chest with controlled movement.",
    muscleGroups: ["chest", "triceps", "shoulders"]
  },
  {
    name: "Deadlift",
    description: "A compound movement where you lift a barbell from the ground to hip level, emphasizing posterior chain strength.",
    image: "images/deadlift.png",
    alt: "Person lifting a barbell from the floor to hip height with a straight back and engaged core.",
    muscleGroups: ["glutes", "hamstrings", "lower back", "core", "forearms"]
  },
  {
    name: "Bent-Over Row",
    description: "A pulling exercise performed by hinging at the hips and rowing weight toward your torso.",
    image: "images/row.png",
    alt: "Person bent at the hips pulling a barbell toward their torso while keeping their back flat.",
    muscleGroups: ["upper back", "lats", "biceps", "rear delts"]
  },
  {
    name: "Strict Press",
    description: "An overhead pressing movement performed without leg drive, focusing on shoulder and upper-body strength.",
    image: "images/overhead.png",
    alt: "Person pressing a barbell overhead from shoulder level without using leg drive.",
    muscleGroups: ["shoulders", "triceps", "upper chest", "core"]
  },
  {
    name: "Dumbbell Lunge",
    description: "A unilateral lower-body exercise where you step forward or backward into a lunge while holding dumbbells.",
    image: "images/lunge.png",
    alt: "Person stepping into a lunge while holding dumbbells at their sides, front knee bent and back knee near the ground.",
    muscleGroups: ["quadriceps", "glutes", "hamstrings", "calves", "core"]
  }
];

const box = document.getElementById('exercise-library');
const input = document.getElementById('search');
const button = document.getElementById('searchBtn');
const modal = document.querySelector('dialog');
const close = document.querySelector('.close');

// Break apart the array and build each individualy
function init() {
    exercises.forEach(displayExercises);
}

// Assign proper content to each exercise tile
function displayExercises(exercise) {
    const tile = document.createElement('article');
    tile.className = 'exercise-tile';

    let html = `
        <h3 class="name">${exercise.name}</h3>
        <p class="desc">${exercise.description}</p>
    `
    tile.innerHTML = html;
    box.appendChild(tile);

    tile.addEventListener('click', () => populateModal(exercise));
}

// Populate and prepare the modal
function populateModal(exercise) {
    modal.querySelector('h3').textContent = exercise.name;
    modal.querySelector('.modalDesc').textContent = exercise.description;

    let img = modal.querySelector('img');
    img.src = exercise.image;
    img.alt = exercise.alt;

    let tagBox = modal.querySelector('.tags');
    let tagList = tagTemplate(exercise.muscleGroups)
    tagBox.innerHTML = tagList;

    modal.style.display = 'flex';
    openModal();
}

// Open the pre-prepared modal
function openModal() {
    modal.showModal();
}

// Map and prepare muscle group tags
function tagTemplate(tags) {
    return tags.map((tag)=> `<button>${tag}</button>`).join(' ');
}

// Close modal on 'X' click
close.addEventListener('click', () => {
    modal.close();
    modal.style.display = 'none';
})

// Search bar functinality - filter alphaetically by name
button.addEventListener('click', () => {
    let value = input.value;

    let filtered = exercises.filter(function(exercise){
        return (
            exercise.name.toLowerCase().includes(value.toLowerCase()) ||
            exercise.muscleGroups.find(tag => tag.toLowerCase().includes(value.toLowerCase()))
        )
    })

    function compare(a, b) {
    if (a.name < b.name) {
        return -1;
    } else if (a.name > b.name) {
        return 1;
    }
    return 0;
    }

    let sorted = filtered.sort(compare);

    box.innerHTML = "";
    sorted.forEach(function(exercise){
        displayExercises(exercise);
    })
})


// Start the program
init();